FROM centos:centos7
MAINTAINER chenshibin
RUN yum install -y curl tar make gcc wget
RUN yum install -y initscripts
RUN cd /usr/local/src && \
    wget  https://github.com/antirez/redis/archive/3.0.0-rc1.tar.gz  && \
    tar -zxvf 3.0.0-rc1.tar.gz && \
    cd redis-3.0.0-rc1 && \
    make && \
    make install && \
    cp /usr/local/src/redis-3.0.0-rc1/src/redis-server  /usr/local/bin/  && \
    cp /usr/local/src/redis-3.0.0-rc1/src/redis-cli  /usr/local/bin/  && \
    cp /usr/local/src/redis-3.0.0-rc1/src/redis-trib.rb  /usr/local/bin/  && \
    mkdir /etc/redis   && \
    mkdir /var/redis   && \
    mkdir /var/redis/log    && \
    mkdir /var/redis/run   && \
    mkdir /var/redis/6379  && \
    cp /usr/local/src/redis-3.0.0-rc1/redis.conf   /etc/redis/redis_6379.conf  && \
    sed -i 's/daemonize no/daemonize yes/' /etc/redis/redis_6379.conf  && \
    sed -i 's/pidfile \/var\/run\/redis.pid/pidfile \/var\/redis\/run\/redis_6379.pid/' /etc/redis/redis_6379.conf && \
    sed -i 's/logfile ""/logfile \/var\/redis\/log\/redis_6379.log/' /etc/redis/redis_6379.conf &&\
    sed -i 's/dir .\//dir \/var\/redis\/6379/' /etc/redis/redis_6379.conf
ADD ./redis  /etc/init.d/
RUN chmod +x /etc/init.d/redis
RUN touch /home/daemonize


EXPOSE 6379

CMD /usr/local/bin/redis-server /etc/redis/redis_6379.conf && tail -f /home/daemonize